### ISSUE TITLE
Error running: instagrapi.exceptions.LoginRequired: login_required

### ISSUE THREAD

**Issue by m-deane** [official-antique/InstaPy2#33]
Hey,

Enjoying the project, however for the last couple of months have been facing this error:

Looks like the instagram api link for https://i.instagram.com/api/v1/tags/[hashtag]/sections/ is no longer valid?

Traceback (most recent call last):
  File "C:\Users\user\miniconda3\lib\site-packages\instagrapi\mixins\private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "C:\Users\user\miniconda3\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/tags/visiticeland/sections/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\OneDrive\Python_projects\Udemy\Web Automation Instagram in Python\InstaPy\unfollow_bot2.py", line 75, in <module>
    session.like(amount=20, iterable=hashtags, type=LikeType.Tags)
  File "C:\Users\user\miniconda3\lib\site-packages\instapy2\instapy2.py", line 236, in like
    medias = self.configuration.media.medias_tag(amount=amount, tag=tag, randomize_media=randomize_media, skip_top=skip_top)
  File "C:\Users\user\miniconda3\lib\site-packages\instapy2\configuration.py", line 108, in medias_tag
    chunk, max_id = self.session.hashtag_medias_v1_chunk(name=tag, max_amount=amount, tab_key="recent", max_id=id)
  File "C:\Users\user\miniconda3\lib\site-packages\instagrapi\mixins\hashtag.py", line 259, in hashtag_medias_v1_chunk
    result = self.private_request(
  File "C:\Users\user\miniconda3\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\user\miniconda3\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\user\miniconda3\lib\site-packages\instagrapi\mixins\private.py", line 327, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

**Comment by jarrodnorwell** [comment]
Should be fixed in the latest version @m-deane

**Comment by m-deane** [comment]
still having this issue, having reinstalled the package and upgrading python to deal with enum errors
